name: Test
on:
  push:
    branches:
    - main
    - master
    - cran-*
    - version-*
    
env: 
  TEST_URL: ${{ secrets.TEST_URL }}

jobs:
  test-job:
  runs-on: ubuntu-latest
  container:
    image: rocker/tidyverse:4
  steps:
    - name: Test
      run: Rscript -e "devtools::test()"
